#! Copyright 2021 VMware, Inc.
#! SPDX-License-Identifier: Apache-2.0

#@ load("@ytt:data", "data")
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "kpack-dependencies.community.tanzu.vmware.com." + data.values.version
spec:
  refName: kpack-dependencies.community.tanzu.vmware.com
  version: #@ data.values.version
  capacityRequirementsDescription: Registry with > 1GB available space
  releaseNotes: ""
  valuesSchema:
    openAPIv3:
      title: kpack.tanzu.vmware.com values schema
      properties:
        repository:
          type: string
          description: docker repository
          examples:
            - registry.io/kpack
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: #@ data.values.bundle_image
      template:
        - ytt:
            paths:
              - "config/"
        - kbld:
            paths:
              - "-"
              - ".imgpkg/images.yml"
      deploy:
        - kapp: {}
